version: '2'

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.19.2-alpine
    ports:
    - "9000:9000"
    - "9001:9001"
    networks:
      - default
      - proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.s3.entrypoints=http"
      - "traefik.http.routers.s3.rule=Host(`s3.${DOMAIN_NAME}` ) "
      - "traefik.http.middlewares.s3-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.s3.middlewares=s3-https-redirect"
      - "traefik.http.routers.s3-secure.entrypoints=https"
      - "traefik.http.routers.s3-secure.rule=Host(`s3.${DOMAIN_NAME}` )   "
      - "traefik.http.routers.s3-secure.tls=true"
      - "traefik.http.routers.s3-secure.tls.certresolver=http"
      - "traefik.http.routers.s3-secure.service=s3"
      - "traefik.http.services.s3.loadbalancer.server.port=9000"
      - "traefik.http.routers.s3-console.entrypoints=http"
      - "traefik.http.routers.s3-console.rule=Host(`s3-console.${DOMAIN_NAME}` ) "
      - "traefik.http.middlewares.s3-console-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.s3-console.middlewares=s3-console-https-redirect"
      - "traefik.http.routers.s3-console-secure.entrypoints=https"
      - "traefik.http.routers.s3-console-secure.rule=Host(`s3-console.${DOMAIN_NAME}` )   "
      - "traefik.http.routers.s3-console-secure.tls=true"
      - "traefik.http.routers.s3-console-secure.tls.certresolver=http"
      - "traefik.http.routers.s3-console-secure.service=s3-console"
      - "traefik.http.services.s3-console.loadbalancer.server.port=9001"
      - "traefik.docker.network=proxy"
networks:
  default:
  proxy:
    external: true


